language: node_js

node_js:
  - '6.0'

cache:
  directories:
    - node_modules

script: npm run build

deploy:
  - api_key: ${API_KEY}
    app:
      dev: rp-staging
      master: research-project
    provider: heroku
    skip_cleanup: true
